type Query {
	program(shortname: String): Program,
	episode(id: String): Episode,

	programs(
		search_param: String,
		limit_to: Int,
		deep: Boolean = false
	): [Program]
},

type Program {
	active: Boolean,
	author: String,
	copyright: String,
	cover_image: String,
	description: String,
	explicit: Boolean,
	image: String,
	itunes_categories: [String],
	language: String,
	name: String,
	organizations: [String],
	owners: [String],
	redirect_url: [String],
	scheduled_time: String,
	shortname: String,
	stream: String,
	subtitle: String,
	tags: String,
	id: String,
	episodes: [Episode]
},

type Episode {
	audio_url: String,
	delay: Int,
	description: String,
	end_time: String,
	explicit: Boolean,
	guid: String,
	hits: Int,
	image: String,
	length: Int,
	name: String,
	pubdate: String,
	start_time: String,
	type: String,
	id: String,
	tracks: [Track]
},

type Track {
	artist: String,
	log_time: String,
	mbid: String,
	title: String,
	id: String
}